### ISSUE TITLE
experiencing with the Zybo development board, where you're seeing a string of seemingly random characters and symbols when connecting to COM6 port, can be described as a communication or serial port problem.

### ISSUE THREAD

**Issue by dhjaber** [xupgit/Zynq-Design-using-Vivado#6]
experiencing with the Zybo development board, where i am seeing a string of seemingly random characters and symbols when connecting to COM6 port, can be described as a communication or serial port problem. Here's a more detailed description of the issue:

Issue Description:

When attempting to communicate with the Zybo development board via the COM6 port, you encounter a problem where the data received appears as a garbled string of characters and symbols. The data does not seem to convey any meaningful information, making it difficult to interact with or control the Zybo board as expected

**Comment by dhjaber** [comment]
jˆn×nñ+%jùmPfr�|%r¦~yª8ã‘¢¡z¡|%r¦~Am·-õ(‡(¦a—h‡jÉ¨§*·à‡(Õêç*§è‡)Ùjñ*Õjçêç-õ(ñ¨ù.•*µªÙmç*"¦-‡ë‡j§«Ç¨§kù«¡\VBªn‚œ@hÙêÁ,«Ñíñj×-Åíu*×'"…(…(…¨†m‡ §m×­¡d€œ@(…(…(…(…(U¨v±6�±±Tzfr€œ@(…(…èÕª‡.åêç-5`±"†a@(…(…(…¬¥iÑ(§-×¨ ™b"…(…(…(…lÀ(‡n×®¡b&¨8f×nñ+¥jùmPå|±»�&a@(…b§«Çè¶+×+ñª×(×ïjh¹¬8(…(…(…a×**×ê×-Å,†a@(…(…(…(…(…è†m×(ÅcÆ,•,§-"…(…(…(ÕmÀ(‡n×®¡+e&¨8(…(…(…hõª‡.åêç-EàV"†a@(…(…(…(©t@v‹Xb¹f$…á©e~Á,eêçhÆ,éiçèñè¶*§*§j âæé§í·.ñ,Õ¨Ab§«Ç(¦-‡ ÇjÉ(‡«ý
Input/output error in writeArray

**Comment by cathalmccabe** [comment]
What com port settings are you using? 
It should be 115200 baud. 

You can see this type of garbled output if you use the wrong baud rate. (9600 can be a default settings)

**Comment by dhjaber** [comment]
I use like what mentioned in this lab1

**Comment by dhjaber** [comment]
I am using Zybo Board

**Comment by dhjaber** [comment]
Solved
